version: "3.7"

services:
  # Duck DNS
  # https://hub.docker.com/r/linuxserver/duckdns
  #   
  # Change the frequency with which the server sends the IP to Duck DNS
  #   docker exec -it PROJECT_NAME_duckdns /bin/bash
  #   crontab -e -u abc
  #
  duckdns:
    image: linuxserver/duckdns:${DUCKDNS_VERSION:-latest}
    container_name: ${PROJECT_NAME}_duckdns
    restart: unless-stopped
    volumes:
      - $DATA/duckdns:/config
    environment:
      - PUID=$PUID #optional
      - PGID=$PGID #optional
      - TZ=$TZ
      - SUBDOMAINS=$DUCKDNS_SUBDOMAIN
      - TOKEN=$DUCKDNS_TOKEN
      - LOG_FILE=true #optional