version: "3.7"

services:
  # Duck DNS
  # https://hub.docker.com/r/linuxserver/duckdns
  #   
  # Change the frequency with which the server sends the IP to Duck DNS
  #   docker exec -it PROJECT_NAME_duckdns /bin/bash
  #   crontab -e -u abc
  #
  duckdns:
    image: linuxserver/duckdns:${DUCKDNS_VERSION:-latest}
    container_name: ${PROJECT_NAME}_duckdns
    hostname: duckdns
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA/duckdns:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SUBDOMAINS=$DUCKDNS_SUBDOMAIN
      - TOKEN=$DUCKDNS_TOKEN
      - LOG_FILE=true