version: "3.7"

services:
  ## FreshRSS
  # https://hub.docker.com/r/linuxserver/freshrss
  freshrss:
    image: linuxserver/freshrss:${FRESHRSS_VERSION:-latest}
    container_name: ${PROJECT_NAME}_freshrss
    hostname: freshrss
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - $DOCKER/freshrss:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.freshrss-rtr.entrypoints=https"
      - "traefik.http.routers.freshrss-rtr.rule=Host(`freshrss.$DOMAIN`)"
      ## Middlewares
      - "traefik.http.routers.freshrss-rtr.middlewares=secure-headers@file"
      ## HTTP Services
      - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
      - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
  db:
    external: true