version: "3.7"

services:
  ## FreshRSS
  # https://hub.docker.com/r/linuxserver/freshrss

  ## Suggested procedure to create your Database:
  ## Change the <password>
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE freshrss CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
    # GRANT ALL PRIVILEGES ON freshrss.* TO 'freshrss'@'freshrss.mariadb' IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit
  freshrss:
    image: linuxserver/freshrss:${FRESHRSS_VERSION:-latest}
    container_name: ${PROJECT_NAME}_freshrss
    hostname: freshrss
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - db
    volumes:
      - $DOCKER/freshrss:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.freshrss-rtr.entrypoints=https"
      - "traefik.http.routers.freshrss-rtr.rule=HostHeader(`freshrss.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.freshrss-rtr.middlewares=secure-headers@file"
      ## HTTP Services
      - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
      - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
  db:
    external: true