version: "3.7"

services:
  ## Jellyfin - Media Server
  # https://hub.docker.com/r/linuxserver/jellyfin
  jellyfin:
    image: linuxserver/jellyfin:${JELLYFIN_VERSION:-latest}
    container_name: ${PROJECT_NAME}_jellyfin
    hostname: jellyfin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    devices:
      - /dev/vcsm:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /opt/vc/lib:/opt/vc/lib
      - $DOCKER/jellyfin/config:/config
      - $DOCKER/jellyfin/cache:/cache
      # media
      - $MEDIA/films:/films:ro
      - $MEDIA/tvshows:/tvshows:ro
      - $MEDIA/music:/music:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      ## HTTP Routers
      - "traefik.http.routers.jellyfin-rtr.entrypoints=https"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`media.$DOMAIN`)"
      - "traefik.http.routers.jellyfin-rtr.tls=true"
      - "traefik.http.routers.jellyfin-rtr.tls.certresolver=digitalocean"
      - "traefik.http.routers.jellyfin-rtr.tls.domains[0].main=$DOMAIN"
      - "traefik.http.routers.jellyfin-rtr.tls.domains[0].sans=*.$DOMAIN"
      ## Middlewares
      - "traefik.http.routers.jellyfin-rtr.middlewares=jellyfin-headers"
      - "traefik.http.middlewares.jellyfin-headers.headers.accesscontrolallowmethods=GET, OPTIONS, PUT"
      - "traefik.http.middlewares.jellyfin-headers.headers.accesscontrolalloworiginlist=https://$DOMAIN"
      - "traefik.http.middlewares.jellyfin-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.jellyfin-headers.headers.addvaryheader=true"
#      - "traefik.http.middlewares.jellyfin-headers.headers.allowedhosts=jellyfin.$DOMAIN"
      - "traefik.http.middlewares.jellyfin-headers.headers.hostsproxyheaders=X-Forwarded-Host"
      - "traefik.http.middlewares.jellyfin-headers.headers.sslredirect=true"
#      - "traefik.http.middlewares.jellyfin-headers.headers.sslhost=jellyfin.$DOMAIN"
#      - "traefik.http.middlewares.jellyfin-headers.headers.sslforcehost=true"
#      - "traefik.http.middlewares.jellyfin-headers.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.jellyfin-headers.headers.stsseconds=63072000"
      - "traefik.http.middlewares.jellyfin-headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.stspreload=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.forcestsheader=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.framedeny=true"
#      - "traefik.http.middlewares.jellyfin-headers.headers.customframeoptionsvalue=SAMEORIGIN" # This option overrides FrameDeny
      - "traefik.http.middlewares.jellyfin-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.browserxssfilter=true"
#      - "traefik.http.middlewares.jellyfin-headers.headers.contentsecuritypolicy=frame-ancestors 'none'; object-src 'none'; base-uri 'none';"
      - "traefik.http.middlewares.jellyfin-headers.headers.referrerpolicy=same-origin"
      - "traefik.http.middlewares.jellyfin-headers.headers.featurepolicy=camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
      - "traefik.http.middlewares.jellyfin-headers.headers.customresponseheaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex,"
      - "traefik.http.middlewares.jellyfin-headers.headers.customframeoptionsvalue=allow-from https:$DOMAIN" # This option overrides FrameDeny
      ## Services
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"

networks:
  proxy:
    external: true