version: '3.7'

services:
  ## Portainer - WebUI for Containers
  # https://hub.docker.com/r/portainer/portainer
  portainer:
    image: portainer/portainer:${PORTAINER_VERSION:-latest}
    container_name: ${PROJECT_NAME}_portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    command: -H unix:///var/run/docker.sock
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DATA/portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      ## HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=https"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAIN`)"
      - "traefik.http.routers.portainer-rtr.tls=true"
      - "traefik.http.routers.portainer-rtr.tls.certresolver=digitalocean"
      - "traefik.http.routers.portainer-rtr.tls.domains[0].main=$DOMAIN"
      - "traefik.http.routers.portainer-rtr.tls.domains[0].sans=*.$DOMAIN"
      ## Middlewares
      - "traefik.http.routers.portainer-rtr.middlewares=no-auth-chain@file"
      ## Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"

networks:
  proxy:
    external: true