version: "3.7"

services:
  ## Postgres – Database
  # https://hub.docker.com/_/postgres
  # 
  ## Create external postgres network:
  #   docker network create db
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: ${PROJECT_NAME}_postgres
    hostname: postgres
    restart: unless-stopped
    networks:
      - db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - $DOCKER/postgres:/var/lib/postgresql/data

networks:
  db:
    external: true
